version: "2"
services:
  wpdb:
    image: mariadb
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
  wp:
    image: wordpress
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    links:
      - wpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: pass
  composer:
    restart: 'no'
    image: composer/composer:php7
    command: install
    volumes:
      - ./:/var/www/html
